<?php
/* Minimum */
define('REGULAR_CLEANING_MINIMUM_BOOKING', 30);
define('REGULAR_LUXURY_CLEANING_MINIMUM_BOOKING', 32);
define('COMMERCIAL_CLEANING_MINIMUM_BOOKING', 32);
define('ANTIVIRAL_SANITISATION_MINIMUM_BOOKING', 200);
define('ANTIVIRAL_SANITISATION_COMMERCIAL_MINIMUM_BOOKING', 600);
define('ONE_OFF_CLEANING_MINIMUM_BOOKING', 125);
define('CARPET_CLEANING_MINIMUM_BOOKING', 85);
define('MATTRESS_CLEANING_MINIMUM_BOOKING', 85);
define('UPHOLSTERY_CLEANING_MINIMUM_BOOKING', 85);
define('WINDOW_CLEANING_MINIMUM_BOOKING', 85);
define('CURTAIN_CLEANING_MINIMUM_BOOKING', 85);
define('OVEN_CLEANING_MINIMUM_BOOKING', 85);
define('RUBBISH_REMOVAL_MINIMUM_BOOKING', 85);
define('AFTER_BUILDERS_CLEANING_MINIMUM_BOOKING', 85);
define('END_OF_TENANCY_CLEANING_FLAT_MINIMUM_BOOKING', 120);
define('END_OF_TENANCY_CLEANING_HOUSE_MINIMUM_BOOKING', 160);
define('HARD_FLOOR_CLEANING_MINIMUM_BOOKING', 100);
define('GARDENING_MINIMUM_BOOKING', 127);
define('WOODEN_FLOOR_MINIMUM_BOOKING', 350);
define('CAR_VALETING_INTERNAL_MINIMUM_BOOKING', 75);
define('CAR_VALETING_EXTERNAL_MINIMUM_BOOKING', 75);
define('CAR_VALETING_MINI_MINIMUM_BOOKING', 75);
define('CAR_VALETING_MIDI_MINIMUM_BOOKING', 80);
define('CAR_VALETING_FULL_MINIMUM_BOOKING', 100);

/* Regular cleaning */
define('REGULAR_CLEANING_PRICE', 20);

/*Regular luxury cleaning */
define('REGULAR_LUXURY_CLEANING_PRICE', 25);

/* Commercial cleaning */
define('COMMERCIAL_CLEANING_PRICE', 20);

/* Antiviral sanitisation */
define('ANTIVIRAL_SANITISATION_PRICE', 2.5);
define('ANTIVIRAL_SANITISATION_COMPUTER_PRICE', 3);
define('ANTIVIRAL_SANITISATION_HOTEL_ROOMS_PRICE', 30);

/* Antiviral sanitisation commercial */
define('ANTIVIRAL_SANITISATION_COMMERCIAL_200_PRICE', 6);
define('ANTIVIRAL_SANITISATION_COMMERCIAL_500_PRICE', 5);
define('ANTIVIRAL_SANITISATION_COMMERCIAL_750_PRICE', 4);
define('ANTIVIRAL_SANITISATION_COMMERCIAL_ABOVE_750_PRICE', 3);
define('ANTIVIRAL_SANITISATION_COMMERCIAL_COMPUTER_PRICE', 6);
define('ANTIVIRAL_SANITISATION_COMMERCIAL_HOTEL_ROOMS_PRICE', 50);

/* One off cleaning */
define('ONE_OFF_CLEANING_PRICE', 28);
define('ONE_OFF_CLEANING_EQUIPMENT_PRICE', 33);
define('ONE_OFF_ECO_NATURAL_INGREDIENTS_PRICE', 30);
define('ONE_OFF_ECO_IONISED_WATER_PRICE', 37);
define('ONE_OFF_ECO_BRAVO_PRODUCTS_PRICE', 27);
define('ONE_OFF_EQUIPMENT_PRICE', 23);

define('ONE_OFF_INSIDE_FRIDGE_PRICE', 25);
define('ONE_OFF_INSIDE_FREEZER_PRICE', 25);
define('ONE_OFF_INSIDE_CUPBOARDS_PRICE', 50);
define('ONE_OFF_INSIDE_CUPBOARDS_MEDIUM_PRICE', 70);
define('ONE_OFF_INSIDE_CUPBOARDS_LARGE_PRICE', 90);
define('ONE_OFF_WOODEN_BLINDS_PRICE', 10);
define('ONE_OFF_GLASS_PANEL_PRICE', 25);

/* Carpet cleaning */
define('CARPET_STEAM_STAIRS_PRICE', 40);
define('CARPET_STEAM_LOUNGE_PRICE', 105);
define('CARPET_STEAM_DINING_PRICE', 65);
define('CARPET_STEAM_KITCHEN_PRICE', 25);
define('CARPET_STEAM_BEDROOM_PRICE', 50);
define('CARPET_STEAM_DOUBLE_BEDROOM_PRICE', 55);
define('CARPET_STEAM_HALLWAY_PRICE', 40);
define('CARPET_STEAM_LANDING_PRICE', 25);
define('CARPET_STEAM_BATHROOM_PRICE', 25);
define('CARPET_STEAM_MEDIUM_RUG_PRICE', 50);
define('CARPET_STEAM_LARGE_RUG_PRICE', 65);

define('CARPET_DRY_STAIRS_PRICE', 75);
define('CARPET_DRY_LOUNGE_PRICE', 135);
define('CARPET_DRY_DINING_PRICE', 95);
define('CARPET_DRY_KITCHEN_PRICE', 30);
define('CARPET_DRY_BEDROOM_PRICE', 65);
define('CARPET_DRY_DOUBLE_BEDROOM_PRICE', 75);
define('CARPET_DRY_HALLWAY_PRICE', 55);
define('CARPET_DRY_LANDING_PRICE', 45);
define('CARPET_DRY_BATHROOM_PRICE', 30);
define('CARPET_DRY_MEDIUM_RUG_PRICE', 70);
define('CARPET_DRY_LARGE_RUG_PRICE', 85);

	
/* Mattress cleaning */
define('MATTRESS_STEAM_BABYCOT_PRICE', 15);
define('MATTRESS_STEAM_SINGLE_PRICE', 35);
define('MATTRESS_STEAM_DOUBLE_PRICE', 50);
define('MATTRESS_STEAM_QUEEN_SIZE_PRICE', 60);
define('MATTRESS_STEAM_KING_SIZE_PRICE', 70);

define('MATTRESS_DRY_SINGLE_PRICE', 60);
define('MATTRESS_DRY_DOUBLE_PRICE', 60);
define('MATTRESS_DRY_QUEEN_SIZE_PRICE', 65);
define('MATTRESS_DRY_KING_SIZE_PRICE', 70);

	
/* Upholstery cleaning */
define('UPHOLSTERY_STEAM_TWO_SEATER_FABRIC_PRICE', 75);
define('UPHOLSTERY_STEAM_THREE_SEATER_FABRIC_PRICE', 90);
define('UPHOLSTERY_STEAM_FIVE_SEATER_FABRIC_PRICE', 105);
define('UPHOLSTERY_STEAM_ARMCHAIR_FABRIC_PRICE', 53);
define('UPHOLSTERY_STEAM_DINING_CHAIR_PRICE', 18);
define('UPHOLSTERY_STEAM_TWO_SEATER_LEATHER_PRICE', 75);
define('UPHOLSTERY_STEAM_THREE_SEATER_LEATHER_PRICE', 90);
define('UPHOLSTERY_STEAM_FIVE_SEATER_LEATHER_PRICE', 105);
define('UPHOLSTERY_STEAM_ARMCHAIR_LEATHER_PRICE', 53);
define('UPHOLSTERY_STEAM_HEADBOARD_PRICE', 10);

define('UPHOLSTERY_DRY_TWO_SEATER_PRICE', 100);
define('UPHOLSTERY_DRY_THREE_SEATER_PRICE', 120);
define('UPHOLSTERY_DRY_FIVE_SEATER_PRICE', 170);
define('UPHOLSTERY_DRY_ARMCHAIR_PRICE', 75);
define('UPHOLSTERY_DRY_DINING_CHAIR_PRICE', 50);

define('UPHOLSTERY_STEAM_TWO_SEATER_LSHAPED_FABRIC_PRICE', 75);
define('UPHOLSTERY_STEAM_THREE_SEATER_LSHAPED_FABRIC_PRICE', 95);
define('UPHOLSTERY_STEAM_FOUR_SEATER_LSHAPED_FABRIC_PRICE', 115);
define('UPHOLSTERY_STEAM_FIVE_SEATER_LSHAPED_FABRIC_PRICE', 130);

define('UPHOLSTERY_STEAM_TWO_SEATER_LSHAPED_LEATHER_PRICE', 115);
define('UPHOLSTERY_STEAM_THREE_SEATER_LSHAPED_LEATHER_PRICE', 135);
define('UPHOLSTERY_STEAM_FOUR_SEATER_LSHAPED_LEATHER_PRICE', 150);
define('UPHOLSTERY_STEAM_FIVE_SEATER_LSHAPED_LEATHER_PRICE', 175);

/* Window cleaning */
define('WINDOW_SMALL_PRICE', 9);
define('WINDOW_MEDIUM_PRICE', 12);
define('WINDOW_LARGE_PRICE', 12);
define('WINDOW_BAY_PRICE', 24);
define('WINDOW_FRENCH_DOOR_PRICE', 15);


/* Curtain cleaning */
define('CURTAIN_STEAM_SHORT_PRICE', 45);
define('CURTAIN_STEAM_FULL_LENGTH_PRICE', 55);
define('CURTAIN_DRY_SHORT_PRICE', 55);
define('CURTAIN_DRY_FULL_LENGTH_PRICE', 60);

/* After builders cleaning */
define('AFTER_BUILDERS_CLEANING_PRICE', 29);
define('AFTER_BUILDERS_EQUIPMENT_CLEANING_PRICE', 36);

/* Oven cleaning */
define('OVEN_GAS_HOBS_PRICE', 26);
define('OVEN_GAS_HOBS_DOUBLE_PRICE', 31);
define('OVEN_CERAMIC_HOBS_PRICE', 24);
define('OVEN_SINGLE_PRICE', 80);
define('OVEN_DOUBLE_PRICE', 93);
define('OVEN_MICROWAVE_PRICE', 60);
define('OVEN_EXTRACTOR_PRICE', 26);
define('OVEN_EXTRACTOR_DOUBLE_PRICE', 31);

define('OVEN_RANGE_OVEN_PRICE', 83);
define('OVEN_RANGE_HOOD_PRICE', 38);
define('OVEN_RANGE_GAS_HOBS_PRICE', 30);
define('OVEN_RANGE_ELECTRIC_HOBS_PRICE', 25);
define('OVEN_RANGE_CERAMIC_HOBS_PRICE', 20);
define('OVEN_RANGE_EXTRACTOR_PRICE', 39);
define('OVEN_RANGE_WIDE_PRICE', 78);
define('OVEN_RANGE_HALF_SIZE_PRICE', 55);
define('OVEN_WARMING_DRAWER_PRICE', 14);
define('OVEN_MASTER_RANGE_90_PRICE', 154);
define('OVEN_MASTER_RANGE_100_PRICE', 169);

define('OVEN_TWO_SIZE_PRICE', 124);
define('OVEN_FOUR_SIZE_PRICE', 147);
define('OVEN_SIDE_MODULE_PRICE', 66);

define('OVEN_SMALL_BBQ_PRICE', 70);
define('OVEN_LARGE_BBQ_PRICE', 95);

/* Oven combo deals */
define('SINGLE_OVEN_HOB_EXTRACTOR', 106);
define('DOUBLE_OVEN_HOB_EXTRACTOR', 124);
define('MASTER_RANGE_90_HOB_EXTRACTOR', 149);
define('MASTER_RANGE_100_HOB_EXTRACTOR', 164);

/* Hard floor cleaning */

define('HARD_FLOOR_REGULAR_PRICE', 4);
define('HARD_FLOOR_WOOD_PRICE', 6);

/* Wooden floor services */

define('WOODEN_FLOOR_SERVICE_1', 12);
define('WOODEN_FLOOR_SERVICE_2', 18);
define('WOODEN_FLOOR_SERVICE_3', 3);
define('WOODEN_FLOOR_SERVICE_4', 2);
define('WOODEN_FLOOR_SERVICE_5', 20);
define('WOODEN_FLOOR_SERVICE_6', 20);
define('WOODEN_FLOOR_SERVICE_7', 5);
define('WOODEN_FLOOR_SERVICE_8', 5);
define('WOODEN_FLOOR_SERVICE_9', 4);
define('WOODEN_FLOOR_SERVICE_10', 10);
define('WOODEN_FLOOR_SERVICE_11', 25);
define('WOODEN_FLOOR_SERVICE_12', 12);
define('WOODEN_FLOOR_SERVICE_13', 45);
define('WOODEN_FLOOR_SERVICE_14', 30);
define('WOODEN_FLOOR_SERVICE_27', 35);

//Solid wood floor installation prices

define('WOODEN_FLOOR_SERVICE_15', 20);
define('WOODEN_FLOOR_SERVICE_16', 35);
define('WOODEN_FLOOR_SERVICE_17', 12);

//Engineered wood floor fitting prices

define('WOODEN_FLOOR_SERVICE_18', 15);
define('WOODEN_FLOOR_SERVICE_19', 20);
define('WOODEN_FLOOR_SERVICE_20', 6);
define('WOODEN_FLOOR_SERVICE_21', 40);

//Laminate floor fitting prices

define('WOODEN_FLOOR_SERVICE_22', 15);
define('WOODEN_FLOOR_SERVICE_23', 20);
define('WOODEN_FLOOR_SERVICE_24', 6);
define('WOODEN_FLOOR_SERVICE_25', 40);
define('WOODEN_FLOOR_SERVICE_26', 40);

/* End of tenancy */

/* Prices are in script.js */ 

define('END_OF_TENANCY_KEYS_NEAR_PRICE', 10);
define('END_OF_TENANCY_KEYS_FAR_PRICE', 20);


/* Gardening */

define('GARDENING_PRICE', 60);
define('RUBBISH_CLEARANCE_SMALL_BAG_PRICE', 4.5);
define('RUBBISH_CLEARANCE_JUMBO_BAG_PRICE', 60);

/* Car Valeting */
$carValetingCityCarPrices = ['internal' => 60, 'external' => 60, 'mini' => 65, 'midi' => 80, 'full' => 100];
$carValetingSpaceCruisePrices = ['internal' => 60, 'external' => 60, 'mini' => 80, 'midi' => 100, 'full' => 120];
$carValetingFourByFourPrices = ['internal' => 80, 'external' => 80, 'mini' => 100, 'midi' => 120, 'full' => 140];
$carValetingVanPrices = ['internal' => 80, 'external' => 100, 'mini' => 160, 'midi' => 200, 'full' => 260];


/* Rubbish removal */
$rubbishCubicYardsPrices = array(
	1 => 62,
	3 => 94,
	6 => 129,
	9 => 165,
	12 => 199
);

$rubbishWeightPrices = array(
	70 => 62,
	150 => 74,
	250 => 94,
	330 => 109,
	410 => 129,
	500 => 144,
	600 => 165,
	680 => 178,
	760 => 199,
	830 => 219,
	900 => 242,
	1000 => 264
);

